### PR TITLE
Updated Audio buttons to fill the width of the frame

### LINKED ISSUE #125: Improve styling of audio sessions section
**Describe the feature that you would like added**
There is a section on the left of the application that displays all of the audio sessions that have been created. However, the buttons are condensed to one side of the section, rather than taking up the full width of the section. Also, the scrollbar displays all the time, even if it is not needed.

**Tasks that need to completed for this feature**

- [x] Configure the audio session buttons so that they take up as much of the width of the section as possible
- [ ] Only display the scrollbar if there is overflow in the section

**Additional context**
image

### PR DESCRIPTION
**Pull request by cbush201**
Fixes #125
(partially)

Unfortunately, CustomTKinter does not have a way to hide the scrollbar in a ScrollableFrame. I have found an addon created by another user, but I would prefer to get permission from Logan before using it since it has a license of sorts. (https://github.com/Akascape/CTkXYFrame)

**What was changed?**

- Edited the createButton() function to allow for width input on call. 
- Edited new_audio() to use the ScrollableFrame's width as input for new buttons. 

**Why was it changed?**

The function createButton() is useful for creating buttons and adding them to the grid in one task, but needed to expand its parameter entry to account for setting a custom width. 

See lines 29 and 440-442 for changes. 

**Screenshots that show the changes (if applicable):**

image

### CODE REVIEW

**Comment by loganwyas** [comment]
@cbush201 I just got confirmation that you can use this add-on, as long as (a) you include the original license (which should already be done if you directly clone the repo, and (b) make a comment next to the import that mentions it is from a third-party license.

**Comment by cbush201** [comment]
Pylint seems to not be able to find the new Library, but it builds and runs just fine on my end. I'm assuming I've missed a step in adding the third-party code. @loganwyas , Let me know how to best proceed. Once that's fixed, the new frame is implemented and functional. Additionally, the 2-axis scroll allows for better visibility if longer names are entered. Screenshots attached. 

image

image

image

**Comment by loganwyas** [comment]
@cbush201 When I run the code, I am getting the same errors as pylint, so I'm assuming it is more of a git-related issue. Take a look at this link: https://git-scm.com/book/en/v2/Git-Tools-Submodules.

**Comment by cbush201** [comment]
I'm honestly lost as to what is wrong with it at this point. @loganwyas can you try following the steps here? If that doesn't work I can ask Dr. Holdener afterwards. My last solution will probably be to brute force and add every file to our repo manually. 
image

**Comment by loganwyas** [comment]
@cbush201 When I ran "git submodule init", it gave me a "No url found for submodule path 'CTkXYFrame' in .gitmodules". I played around with the .gitmodules file a bit and was able to get it to work with the following: 
image

After making this modification, I would also modify the GitHub Action for Pylint so that it runs the proper commands for this to work, along with adding a note in the documentation to do this upon cloning the repo.

**Comment by cbush201** [comment]
@loganwyas finally fixed, thanks for your help. Hopefully everything works on your end.

**Review by loganwyas — APPROVED** [review]

**Pull request merged**
