### PR TITLE
attempting to add diarazation capabilities

### LINKED ISSUE #58: Use diarization to identify and attempt to label speakers
Using a diarization library that can identify and label speakers may drastically speed up the user's workflow. Note that as of writing this issue (4/14/23), all diarization libraries appear to be paid for or very difficult to use. If a library becomes available, commented-out code in diarizationAndTranscription.py can be used as a guide for this issue.

### PR DESCRIPTION
**Pull request by JackPifer**
Work on issue #58

**What was changed?**

*Added code to start diarization process, does not work yet.*

**Why was it changed?**

*It is a necessary function of the application.*

**How was it changed?**

*I added code from the pyannote library that i supposed to allow for transcription... to be determined if it actually works as intended.*

**Screenshots that show the changes (if applicable):**

### CODE REVIEW

**Comment by loganwyas** [comment]
@JackPifer What is the progress on this?

**Comment by JackPifer** [comment]
> @JackPifer What is the progress on this?

Still in progress, the approach I was initially didn't work as intended. Working on it now

**Comment by JackPifer** [comment]
Fixes https://github.com/oss-slu/SpeechTranscription/issues/58
(except not entirely)
What was changed?

Used py.annote to attempt to diarize the audio file. 

Why was it changed?

It is a necessary function of the application.

How was it changed?

I added code from the pyannote library that i supposed to allow for transcription. However, this current version of the code does not work with whisper the way I intend it to and raises a few issues when run. First, there is some issue with the threading, however the program still behaves as if it is running a thread for the diarization and transcription process so I am not sure what is going on there. The main problem, however, is that whisper does not have the capability to show timestamps of the different lines of text that it grabs from the audio. Without this, the py.annote library has to try and transcribe the text itself which is not nearly as good as whispers capabilities. It also does not grab consistent timestamps of its own and so the audio that it does gather is chopped up in an unnatural way. It took a long time to get to this point but I am looking for potential solutions or alternatives to the approach that allow for us to accomplish our goal, unfortunately there do not seem to be very many good options at the moment.

Screenshots that show the changes (if applicable):

**Comment by loganwyas** [comment]
@JackPifer There's a few things I noticed when running that should be fixed:

- Add the new packages to "requirements.txt"
- When I attempt to transcribe any audio files, I am given an error and the program stalls (given more errors with .mp3 files)

If the program can run without errors and has a noticeable change related to the issue, then I will merge it. But I will keep the issue this PR is attached to open, because this seems to be something that even last year's developers struggled with.

**Comment by JackPifer** [comment]
Work on issue https://github.com/oss-slu/SpeechTranscription/issues/58

What was changed?

Tried a different approach for diarization than before.  Goal is to do my best to combine the abilities of Pyannote and Whisper libraries in order to build a cohesive, correct, and labeled transcript

Why was it changed?

It is a necessary function of the application.

How was it changed?

Started to use pyannote to find speaker timestamps, trying to align the pyannote audio with whisper transcription and see if it works and shows proper transcription and diarization

Screenshots that show the changes (if applicable):

**Comment by loganwyas** [comment]
@JackPifer How is this coming along?

**Comment by loganwyas** [comment]
@JackPifer Before this gets merged, please fix the merge conflicts

**Review by loganwyas — APPROVED** [review]

**Pull request merged**
