### PR TITLE
Added .docx to gitignore file. FIXES #52

### LINKED ISSUE #52: gitignore docx
Add .docx to the gitignore file so that exported documents dont wind up into the git.

### PR DESCRIPTION
**Pull request by TravisHerrick7**
Fixes #52 

You can see my changes by viewing the .gitignore file or after you download the transcript to a doc, you will see that it now does not wind up in the git repo as the .docx files previously used to end up in the git repo. The .gitignore file was the only file edited.

**What was changed?**
I add *.docx to the .gitignore file.

*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
I changed the .gitignonre file by adding "*.docx" to it.

**Why was it changed?**
It was changed because the .docx files were winding up in the git repo when they didn't need to be.

*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
I am fixing the issue where .docx files wind up in the git repo. My code fixes it because I added "*.docx" to the .gitignore file so .docx files should no longer wind up in the repo.

**How was it changed?**
It was changed by adding "*.docx" to the .gitignore file.

*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*
I modified the .gitignore file. The most important line I modified is where I added "*.docx".

**Screenshots that show the changes (if applicable):**
N/A

I also removed the "2023-03-09_SALT_Transcription.docx" file from the repo as we do not want .docx files in the repo.

### CODE REVIEW

**Comment by loganwyas** [comment]
@TravisHerrick7 Is this issue finished, or is there still work to do?

**Comment by TravisHerrick7** [comment]
> @TravisHerrick7 Is this issue finished, or is there still work to do?

Finished.

**Comment by loganwyas** [comment]
@TravisHerrick7 Since we're ignoring docx files, could you remove all of the ones that are already in the repo?

**Comment by TravisHerrick7** [comment]
> @TravisHerrick7 Since we're ignoring docx files, could you remove all of the ones that are already in the repo?

Yes

**Comment by loganwyas** [comment]
I will hold off on merging until you have removed the docx files from the repo. (I see that there is at least one in the root directory.)

**Review by loganwyas — APPROVED** [review]

**Pull request merged**
