### PR TITLE
Fixes #47

### LINKED ISSUE #47: Store transcription states as variables
The transcriptions and info from tables are simply stored there and grabbed from there. This should really be saved and used in variables.

### PR DESCRIPTION
**Pull request by JackPifer**
… it wrong.
The original issue says to assign variables to the transcription instead of getting it from the table every time (it is very vague), however, it seems like that is already done. The original transcription is assigned to transcribedAudio in the transcribe() function and put into the transcription box. Then, any other times that the transcribed audio needs to be accessed, it is taken from the table and assigned to a variable in order to be used. I think this is what it is talking about, but the scopes of the functions don't allow them to be accessed without getting them from the table. Unless this were assigned to a global variable I am not sure how these should/could be implemented. I could also be interpreting the meaning of this incorrectly and be missing what is required, so I will ask in slack to see if any previous members know what it means.

### CODE REVIEW

**Comment by kate-holdener** [comment]
@jakewahle @ahediger Do you have any thoughts about this?

**Comment by jakewahle** [comment]
In terms of Issue #47, it has two parts (one of which is seemingly already done). The one that appears to already be done is to store session info such as client name, date, etc. in variables which is achieved in lines 352-359 in GUI.py. The other part is to store the transcription in a variable as well. So instead of using self.transcriptionBox.get(), for example, you could just update a variable self.<variableName> whenever the user makes changes to text in that box. 

If there is not a convenient way to update that variable whenever the user edits the text, however, it might be best to leave it how it is and close the issue. (Idea: Maybe make a function that updates the text in the transcription variable, so you could update variable -> pass variable instead of create new variable -> send new variable). Up to your discretion though what you think would be cleanest.

Drew might also have some things to add about this, I'm not sure.

**Comment by kate-holdener** [comment]
Thank you @jakewahle! 

@ahediger do you have any thoughts on this?

**Comment by loganwyas** [comment]
@JackPifer Please adjust the title and description of this pull request to reflect the issue that it is fixing. Also, make sure to include "Fixes #<issue_number>"

**Comment by loganwyas** [comment]
@JackPifer I just noticed that there are also merge conflicts, so make sure to resolve these along with changing the description of this PR

**Comment by JackPifer** [comment]
Transcription Box text is now stored in a 'self' variable and can be accessed easier. It is also updated every time the text in the transcription box is changed

**Review by loganwyas — APPROVED** [review]

**Pull request merged**
